### ISSUE TITLE
Output generated setup.py to project folder.

### ISSUE THREAD

**Issue by rochacbruno** [takluyver/flit#135]
Hi,

I found a case where I need to keep the `setup.py` on the root of my repo.

Sometimes changes are commited to repository, but not yet released to PyPI, specially for staging and dev branches one is able to do.

```bash
pip install http://github.com/myname/myrepo/tarball/master
```

The above is a common use case and `pip` looks for a `setup.py` to perform the installation.

I see that `flit` generates a setup.py and packages it on the sdist, I am using a script to extract it, but I wonder if a `flit build --output` or something like this is possible?

* another idea is to allow callbacks/hooks

`flit.ini`
```ini
[post-hooks]
my_post_script:hook
```

So after `flit [anything]` that hook is executed receiving the current `sys.args` as parameter.

**Comment by takluyver** [comment]
We're working on PEP 517, which will allow `pip` to install from a source directory or URL without needing `setup.py`.

I'm against adding `setup.py` into repositories using flit: it either contains duplicate information which can get outdated, or it can't do everything people will want to do with it, or it involves some ugly code I don't want to maintain to integrate flit and setuptools.

In the meantime, you can of course do what you're doing and use the setup.py from an sdist. But it's not something I'm going to encourage by providing any easier way to do it.

You might also want to look at [pbr](https://docs.openstack.org/pbr/latest/) - that's another packaging effort which tries to extend setuptools rather than avoiding it like flit does.
