### ISSUE TITLE
flit's README isn't rendering properly in PyPI

### ISSUE THREAD

**Issue by Mariatta** [takluyver/flit#148]
See: https://pypi.org/project/flit/

**Comment by takluyver** [comment]
Embarrassingly, Flit did actually warn me of this before I uploaded, but I ignored it and hoped it would work anyway. The issue was the sample toml file in the README: pygments doesn't have a lexer for toml yet.

I've uploaded a new release and marked the block as ini syntax for now, which pygments can handle.

**Comment by techtonik** [comment]
https://bitbucket.org/birkenfeld/pygments-main/issues/1150/new-lexer-request-toml-rust

**Comment by takluyver** [comment]
Thanks, I've voted for that.

**Comment by Mariatta** [comment]
Thanks! :)
