### ISSUE TITLE
--pth-file and --python don't work together

### ISSUE THREAD

**Issue by monkeez** [takluyver/flit#164]
I'm trying to use Flit to work on a Python 2.7 project and the `flit install` command is causing me some issues. I have Python 3.6 installed and I have Flit installed with [pipsi](https://github.com/mitsuhiko/pipsi) to keep it isolated from my system Python.

When I run `flit install --pth-file --python ~/example/virtualenv/path/python.exe` a .pth file is created in my virtualenv but none of the dependencies are installed in the virtualenv, they're installed in the environment that Flit was run from.

Is this the intended behaviour?

**Comment by monkeez** [comment]
```
flit install --pth-file --python ~/example/virtualenv/path/python.exe
flit install --python ~/example/virtualenv/path/python.exe
```
Seems to be a work around, but doing this still installs all the requirements to the environment Flit is installed to as well which doesn't seem ideal.

**Comment by takluyver** [comment]
There's a complication in that Flit *might* need the dependencies installed in the environment it's running in, so that it can import your package to get the version number and docstring. In some circumstances it can get those from the AST without loading the package, but not always.

It definitely should install the dependencies into the target Python, but avoiding installing them into the Python flit runs on is trickier.
