### ISSUE TITLE
--repo flag and --verify<bool>

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#17]
Seem like both --upload and --verify take a repo_name as argument  which is the same args, 

Seems little bit weird as  `flit wheel --upload foobar --verify qux` does not make sens. 

I would add a --pypi or --repo flag, with default that can be read from config.

**Comment by takluyver** [comment]
The repo name is kind of a hidden option - I mainly added it so that I could test flit itself against testpypi. Maybe a separate option would be better, though it seems a bit odd for it to be a wheel option.

It also doesn't really make sense to use both --verify and --upload in one command - uploading effectively implies verification.

**Comment by takluyver** [comment]
`--repository` flag added
