### ISSUE TITLE
Do not include pyproject.toml in sdists

### ISSUE THREAD

**Issue by merwok** [takluyver/flit#218]
I am trying to convert a simple lib to flit, and I have to adapt my tox config and CircleCI config.

To test with Python 2.7, the CI config uses a Python 3.6 image to run `tox --sdistonly`, which uses Python 3 to install flit and create an sdist.  Then tox can create a python2.7 environment to install that sdist and run tests.

This plan fails because pip sees `pyproject.toml` and tries to install flit.
If the tarball contained only setup.py, pip install would work on Python 2.

**Comment by merwok** [comment]
This is a workaround:

```
# tox.ini
[testenv:py27]
install_command = python -m pip install --no-build-isolation {opts} {packages}
```

(in addition to the CI config to run `tox --sdistonly` using Python 3)

**Comment by takluyver** [comment]
I view the `setup.py` in sdists at the moment as a shim until pip properly supports PEP 517 to install from source. So leaving out `pyproject.toml`, the new standard metadata definition, definitely seems like the wrong way to go. It's a key part of the source you are distributing.

Unfortunately I have no good answer at the moment for how to install a project from source in Python 2. Flit was written before we defined all the PEP 517/518 mechanisms, and I assumed that we could generate wheels (a standardised format) in Python 3 and install them to Python 2. The 517/518 mechanisms all implicitly assume that the build system runs in the target environment. I really don't want to make Flit Py2 compatible now. Maybe the only realistic way is to say Flit is only for packages that require Python 3. 

I was very reluctant to add `setup.py` for a long time precisely because of this kind of thing: once you've got a setup.py anywhere, it's easy to assume that everything should work the way we're used to with setuptools, which is precisely what I was trying to get away from.

**Comment by merwok** [comment]
IMO it would make sense to produce backward-compatible sdists at the moment (setup.py, no pypackage.toml) to get pip and other tools to use legacy mechanism, and switch to only pypackage.toml when pip gets full support (or alternatively with an option like `flit build --format sdist-legacy`)

**Comment by merwok** [comment]
And in case this isn’t clear: for my project that still supports Python 2.7, I did find a not-too-inelegant work-around to run flit with Python 3 and install the sdist with Python 2.

So this is a nice to have, and will be fully irrelevant when nobody uses Python 2.7.

**Comment by takluyver** [comment]
With flit 2, packages can be installed from source on Python 2 - if you change the build-system section of `pyproject.toml` to look like this:

```toml
[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"
```

At present, hopefully, tools which know about PEP 517 should be able to build with `flit_core`, while tools which don't will fall back to the generated `setup.py`. One day in the future, we'll stop generating `setup.py` and just rely on pyproject.toml.
