### ISSUE TITLE
Shutil.ignore_patterns '.*' ?

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#23]
Does it make sens to ignore hidden files ? like backup file, or swap files ?

(or at least warn that some have been found)

**Comment by takluyver** [comment]
`.svn` would be a bigger problem, I guess. But on the other hand, code could also be using those hidden files, and I don't want to break that by excluding everything.

I have thought about having an 'exclude' option in the config file so the user can specify globs to exclude.

**Comment by mehdisadeghi** [comment]
I found this issue looking for a solution to ignore non-source files from the wheel built by flit. I have also read most of the discussions regarding src directory (#115) but I think it is irrelevant in this case.

Is there any way/trick to ignore files while issuing `flit build`? We have many files which are tracked in git for testing, benchmarks, docs, etc. which we don't want to add to the package, mainly to keep the the package clutter-free and small.

**Comment by mehdisadeghi** [comment]
I just compared the contents of flit installed package on my machine with flit's git repository contents. They are different, i.e. the installed package is basically the `flit` folder in the repo. However when I package [my repo](https://github.com/hiposfer/osmtogtfs/blob/flit/pyproject.toml), flit packages everything it finds in the root of the git repository. Could someone perhaps shed some light on this?

**Comment by takluyver** [comment]
Files outside the package itself should be included in the sdist, but not the wheel. People installing your package will normally get the wheel, which should be relatively small.

The rationale here is that the sdist (source distribution) should contain everything you need for working on the package, as if you had checked out a tag from version control. Downstream packagers want things like docs and tests to be in the sdist, so that they can use those to prepare their own packages. And if in 10 years time your git repo has disappeared from the internet, the sdists are a backup which someone could use to adopt your project and continue development.

You'll see this in Flit's own packages as well: [the sdist](https://files.pythonhosted.org/packages/6a/55/a25505e3b3f5d804d1a0b6a64c582f4a264697c94862ccf71b8a1c62d16d/flit-1.2.1.tar.gz) includes docs and tests, while [the wheel](https://files.pythonhosted.org/packages/f1/52/f4e076e1fa21917183b869349b4188fbc25c2dc228c3be15855480517aed/flit-1.2.1-py3-none-any.whl) doesn't.

Anyway, the original issue here is long out of date; the sdist work all happened after this. So I'm going to close this.

**Comment by mehdisadeghi** [comment]
@takluyver thanks for your quick reply. It was very helpful.
