### ISSUE TITLE
author and author_email is excessive

### ISSUE THREAD

**Issue by techtonik** [takluyver/flit#236]
I understand that there is [metadata that can not be changed](https://packaging.python.org/specifications/core-metadata/#author) to provide author info as a single string:

    __author__ =  "anatoly techtonik <techtonik@gmail.com>

Or even listing all authors in a list (#153). But `flit` is a converter anyway, so it could do this extra conversion step to help people write less boilerplate (and maybe it will become next metadata if people adopt such syntax).

**Comment by dholth** [comment]
It's a weird case, because Author can include an e-mail and Author-email can include a name. Both fields are optional.

**Comment by techtonik** [comment]
Why not clean up the spec from weird cases? Any tracker for weird issues with spec?

**Comment by BuongiornoTexas** [comment]
Would it be possible to make author-email optional rather than required (in line with PEP 345)? 

I'd like to use flit, but I'd strongly prefer to keep my email address private and get people to contact me via github package issues. 

My alternatives seem to be to use a nonsense address or a github no-reply address, both of which would be irritating to anyone trying to contact me, or fall back to using setuptools which appear to allow optional email addresses.

**Comment by takluyver** [comment]
The author email field is now optional (thanks to @wimglenn in PR #289).

For now, I'm going to leave both fields as they are. It is kind of weird, but I'm happy enough just exposing what is used in the metadata. Trying to simplify it would also require thinking about compatibility with existing projects that use both.

If anyone has a concrete proposal for a better way to record author/maintainer information, feel free to open a new issue.
