### ISSUE TITLE
Is Flit project still alive?

### ISSUE THREAD

**Issue by cig0** [takluyver/flit#283]
Hi,

In an excellent article on Pipenv (https://realpython.com/pipenv-guide/), they mention `Flit` as the newer, better alternative to the good old `setuptools` way -- hence I rushed here :)

I'm worried, though, that the project doesn't have had an update in the past three months (what I believe is a valid expectation for a tool like this being actively developed), with even several PR waiting to be merge.

My specific concern is because I don't feel confident about using Flit - for a new project we are looking to push into production soon - if later on be will need to switch to `setuptools`.

Can you tell, thus, what's the state of Flit, if it is being actively developed?

I'd be great to also learn about other people using Flit for they production pipelines and how they feel about it.

BR!

**Comment by takluyver** [comment]
It's more or less alive. I'm only getting scraps of time to work on it, and I'm focussing on the changes that I think are important (see #282) rather than merging other people's changes.

It's also one alternative to setuptools for certain use cases (the simple ones). There are plenty of other projects trying to provide alternatives to packaging with `setup.py` - e.g. [enscons](https://pypi.org/project/enscons/) focussed on more complex cases, or [pbr](https://pypi.org/project/pbr/) which is based on setuptools.

**Comment by flying-sheep** [comment]
Many people depend on it by now. Maybe you should expand the number of maintainers (I’m not volunteering this time, sorry, I have a lot on my plate)

**Comment by takluyver** [comment]
I've managed to find time to work on Flit a bit; 2.0 is out, and 2.1 will probably follow soon.

The next priority will be trying to make it more accessible for other people to work on. There will also be some simplification coming next year (dropping the old `flit.ini` format, in part).
