### ISSUE TITLE
Exclude git submodules from sdist

### ISSUE THREAD

**Issue by McSinyx** [takluyver/flit#323]
I'm [migrating](https://github.com/McSinyx/brutalmaze/commit/b90e6c272c1f76da43992323ffd0f148f759f408) [this project of mine](https://github.com/McSinyx/brutalmaze) from setuptools to flit and cannot seem to be able to get rid of the `wiki` directory which is a git submodule.  `flit build` simply includes an empty directory.

**Comment by takluyver** [comment]
Hi, sorry about that. I guess this is in the sdist (.tar.gz file), not the wheel, right?

At an educated guess, there's a mismatch because git tracks a submodule like a file, but it's a directory on the filesystem. Here's the code which gets the list of files from git:

https://github.com/takluyver/flit/blob/f8afe15b183c03c3dd091ebb4825af7944753b5b/flit/vcs/git.py#L6-L8

And here's the line which should be applying excludes from your `pyproject.toml` file:

https://github.com/takluyver/flit/blob/f8afe15b183c03c3dd091ebb4825af7944753b5b/flit_core/flit_core/sdist.py#L130

At a first thought, maybe we should use the `--recurse-submodules` flag to list the files from the submodule in the same way as the other files git tracks.

**Comment by McSinyx** [comment]
> Hi, sorry about that.  I guess this is in the sdist (.tar.gz file), not the wheel, right?

Please do not be.  There is no way for any of us to foresee every single scenario.  Apart from this, my experience with flit so far is pretty much seamless though.  And yes, I can confirm that the problem does not occur for wheel, probably since the submodule is not inside of a package.

> At a first thought, maybe we should use the --recurse-submodules flag to list the files from the submodule in the same way as the other files git tracks.

Thank you for the insight.  I think that should fix the issue.

**Comment by takluyver** [comment]
Thanks, I'm glad it works for you. :slightly_smiling_face: 

Do you want to make a PR to use that flag? You've got a convenient set-up to test it interactively. Or I can get to it at some point. Be aware that it was just the first idea I had looking through the help for `git ls-files`, so it's possible I'll change my mind and decide that's not the way to go after all.

**Comment by McSinyx** [comment]
> Do you want to make a PR to use that flag? You've got a convenient set-up to test it interactively.

Of course, I'm glad to finish what I've started.

> it's possible I'll change my mind and decide that's not the way to go after all.

That'd be fine, I realized that the directory should be included (and to my surprise it works when `include`'d explicitly), so if there is any change to be made during the upcoming PR, it would not be a problem on my side.
