### ISSUE TITLE
system-wide shell command

### ISSUE THREAD

**Issue by tensionhead** [takluyver/flit#340]
Hello,

I am trying to get flit to also make a shell command available system-wide (no environment). I think I repeated all the steps from the documentation, and also tried to mimic flit's own github repo structure here. For testing I created a dummy project: **https://github.com/tensionhead/flit_scripts_test**

It builds fine, and a 
```
python3 -m flit_scripts_test
```
inside my shell runs the main function. But there is no ```flit_scripts_test``` command available. Any ideas what goes wrong?

**Comment by McSinyx** [comment]
I'm not so sure how `scripts` work but using `[tool.flit.entrypoints.console_scripts]` works for me.

**Comment by tensionhead** [comment]
@McSinyx Thanks for your answer! Actually I got confused from the flit repo and exchanged the
```
[tool.flit.scripts]
```
to 
```
[tool.my_package.scripts]
```
which of course didn't work! Sorry, and what you suggested also works..

**Comment by takluyver** [comment]
It sounds like you've got it working. `[tool.flit.scripts]` and `[tool.flit.entrypoints.console_scripts]` should be mostly the same - although I'm not sure if the latter actually get installed if you do a `--symlink` or `--pth-file` install.

Making it available systemwide depends on how you install it. By default, `flit install` will install into an environment if you're using one, or do a per-user installation otherwise. You can install as root to do a properly systemwide installation, but it's generally not recommended to install Python packages systemwide like that, so Flit requires an environment variable to confirm that's not a mistake.

Properly installing a command-line tool systemwide is a bigger topic, which Flit doesn't try to address. But I'd say there are two main approaches:

- Make a self-contained environment somewhere with all the packages your application needs, and then symlink the command to a directory on PATH (e.g. `/usr/local/bin` on Unix systems). This is roughly what [pipx](https://pypi.org/project/pipx/) does.
- Package it for a system package manager like apt on Ubuntu, or brew on Mac. This can be a lot of work, because of all the different packaging systems out there.

**Comment by tensionhead** [comment]
Just a little follow up: I also mis-used 'system-wide', what I actually meant was on the user level, basically that a command is available on the shell. So I am very happy how it works, and I used the same main() as an entry point for conda successfully. thanks for flit!

**Comment by takluyver** [comment]
Aha, excellent. Yeah, I've spent a fair bit of time thinking about application packaging, where per-user installation is basically the *opposite* of systemwide. Computers... I'm glad it's working for you. :-)
