### ISSUE TITLE
[question] A way to install non-code file into "site-packages" itself

### ISSUE THREAD

**Issue by kshpytsya** [takluyver/flit#349]
I am looking for a way to use `flit` to create a package that would install a file into "site-packages" directory proper (i.e. not into some its sub-directory). I need this to be able to install a `.pth` file, as discussed [here](https://stackoverflow.com/a/57718902/7080242).

BTW, I wasn't able to get the recipe from that post working, but instead came up with the following:

`setup.py`
```py
from setuptools import setup

setup(
    name="xxx1",
    package_dir={"": "src"},
    py_modules=["xxx1"],
    data_files=[("/", ["src/xxx1.pth"])],
)
```

`src/xxx1.pth`
```py
import xxx1
```

`src/xxx1.py`
```py
print("xxx1 imported")
```

According to [this](https://github.com/pypa/wheel/issues/92#issuecomment-409657344), my approach uses an undefined behavior. Moreover, it works only if installing from a wheel, so e.g. `venv/bin/pip install .` fails with an understandable `error: could not create '/xxx1.pth': Permission denied`.

I have seen [this](https://github.com/takluyver/flit/issues/219) but as far as I understand, it only allows files inside package directories.

I am perfectly ok with having `src/xxx1/__init__.py` instead of `src/xxx1.py` (BTW, thanks for finally making the `src` layout possible) but I do need a way to install `.../site-packages/xxx1.pth` file.

**Comment by takluyver** [comment]
Sorry, that's not supported, and not likely to be supported. Flit is very much aimed at the 80% in the 80/20 rule, so if you want to do something unusual, you'll probably need to use another tool.

(I'm also especially disinclined to support this use case, because I think the executable `.pth` files are a misfeature. There are a couple of legitimate use cases - like coverage measurements in subprocesses - that can't currently be done any other way, but I still don't like them.)

**Comment by kshpytsya** [comment]
Kind thanks for your prompt reply. I suppose I will stick to `setup.py` for this particular package. Should you be curious, this is about addition of plugin mechanism to a certain major library, authors of which I believe would not want to include the feature upstream or it would take ages to come up with exact design that would satisfy everyone.
