### ISSUE TITLE
Post-install script / command

### ISSUE THREAD

**Issue by sgraaf** [takluyver/flit#407]
Maybe this is beyond the scope of flit (given its 80/20 nature), but would it be possible to add support for post-install commands / scripts?

If you'd like, I could mock something up and submit a PR.

**Comment by takluyver** [comment]
Post-install scripts are not really a thing in Python packaging in general. It was possible before wheels, but wheels have never supported executing any code from the package being installed, and increasingly that's the default way we expect all installation to work. [This long discussion](https://github.com/pypa/packaging-problems/issues/64) has recently suggested that it would take a PEP to change that, it would probably be a very contentious PEP, and no-one seems motivated enough to write it.

Even if someone did get a PEP accepted for it, I'm inclined to say it's out of scope for Flit. If we've gone 8 years without post-install scripts (since the wheel PEP was accepted), that implies it's on the wrong side of the 80/20 split. Or even the 95/5 split. :wink:

**Comment by sgraaf** [comment]
Fair enough, thank you for the prompt and insightful response :).
