### ISSUE TITLE
Does flit support semver's caret ^=?

### ISSUE THREAD

**Issue by alexchandel** [takluyver/flit#421]
[Semver's ^=](https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json) or “Compatible with version” is often much more useful than PEP 440's ~=, “Approximately equivalent to version”.  [Pipenv and poetry](https://frostming.com/2019/01-04/pipenv-poetry/) both support it.

Does flit support ^=?  Flit's docs say nowhere what requirement syntax is supported.

**Comment by takluyver** [comment]
Flit aims to support precisely what's in the relevant packaging interoperability standards. In this case, that's PEP 440, so `~=` (which is called 'compatible release', not 'approximate', in the Python world) is what's available.

If you want to propose a new operator for specifying versions, the [Packaging board of the Python Discourse forum](https://discuss.python.org/c/packaging/14) would be the place to start.

**Comment by henryiii** [comment]
I really dislike `^` in poetry - it encourages the very bad practice of over-restricting your upper limits. Unless you _know_ something will break on upgrade, or if you really rely heavily on internals (say if you are making a Sphinx plugin, you probably can expect the next release to have a high chance of breaking you). Poetry intentionally recommends this despite [disagreement](https://snarky.ca/why-i-dont-like-semver/) from many of the core Python developers and PyPA members.

As a quick example, one library depends on `click=^7`, and another `click=^8`, you now can't solve your dependencies. There is no _user_ workaround. However, if a library uses `click>=7` and for some weird reason dropping Python 2 and 3.5 support (which is the main change, AFIACT) breaks you, then a _user_ can pin `click<8` and continue happily. ("User" being an end user or a later library).

For an application, it's not so bad (which Poetry is good at and pipenv specializes in). But it's terrible for libraries. I don't think you are likely to get very far trying to add it, IMO.

**Comment by takluyver** [comment]
Closing this as I plan to stick to the version specifiers in the packaging interoperability standards. I don't think it's too much work to expand `foo >=2.3.4,<3` manually if that's what you want.

**Comment by alexchandel** [comment]
@henryiii The point of avoiding `foo>=7.0.0` is that `8.0.0` or `20.0.0` API break compatibility, and usually not by "just dropping Python 2 support." `^=` means "latest compatible version".

@takluyver People and tools default to `foo~=7.0.0`, not `foo>7.0.0` or `foo>=7.0.0`.

**Comment by takluyver** [comment]
We're moving in the direction of standardised metadata - the `[project]` table from PEP 621 ("Each string represents a dependency of the project and MUST be formatted as a valid PEP 508 string"). So now the answer is even clearer: if you want extra comparison operators, you need to propose it as an addition to the packaging standards, not just an enhancement for Flit.

**Comment by henryiii** [comment]
A new version does _not_ promise the portion of the API _you_ use breaks. It just promises something, somewhere breaks. If you are using a fairly stable, reasonable library, the chances that the public, documented API you use breaks is quite low in most cases. Click 9 is very unlikely to break all current users. If you are writing something like a PyTest plugin, you should probably pin to a major version. Otherwise, don't limit! You will force the current version your library to be unusable in the future when it might actually still work.

You are trading a 5-10% chance of breakage that is really easy for users to fix for a 100% chance of forced maintenance on every dependency release, and a broken solve for users in the future. And you still have a 5-10% chance of breakage from bad minor or patch releases anyway.

> People and tools default to `foo~=7.0.0`, not `foo>7.0.0` or `foo>=7.0.0`

No, some tools might default to `foo~=7.0`, I've never seen one default to `foo~=7.0.0`, that would pin on the minor version. Honestly, I don't think I've seen anything default to an upper limit except Poetry, and I'd argue it's usually wrong here.

I don't think you'll be able to convince anyone that `^` is a good idea, but yes, you need to do that to get it in anywhere but Poetry.

Note that some other languages that have `^` isolate each set of dependencies, so library A can require ^7 and library B can require ^8, and the solve still succeeds, because they each get their own dependencies. That is _very_ different from Python, and makes `^` much, much more useful.
