### ISSUE TITLE
Data directories not included in wheel

### ISSUE THREAD

**Issue by octane64** [takluyver/flit#443]
When creating a build for a simple project layout like the following:

project_name
- project_name/
---__init__.py
--- __main__.py
--- module1.py
- data/
--- database.db
--- samplefile.csv
- README.md
- pyproject.toml

Source dist will include data directory alongside project_name dir but wheel will only include project_name dir

**Comment by bpabel** [comment]
You have to include `data` inside your package directory (`project_name/data`). `pip` purposefully makes it difficult to install anything outside the package install directory for security reasons.

**Comment by octane64** [comment]
But data is indeed inside the package directory (outer project_name dir). 
You mean data should be inside the inner project_name dir?

**Comment by takluyver** [comment]
Yup, you need it in the inner directory alongside `__init__.py` - this is the importable module that will get installed. We don't want to install random `.../site-packages/data` directories.

Other Python packaging tools provide a way to install files to other locations - setuptools calls this `data_files`. It's not currently supported in Flit, because I think the situations where you actually need it are limited, and Flit is focused on the simple cases. See #358 for discussion over whether that should be added.
