### ISSUE TITLE
warning instead of error if version string does not match python spec

### ISSUE THREAD

**Issue by evgfaer** [takluyver/flit#53]
There is strong assumption about version string now. If the package is installed, the RequirementParseError: Missing distribution spec error is thrown. Wouldn't it make sense to allow all possible version definitions and just issue a warning is it does not match python spec

**Comment by Carreau** [comment]
Note to @takluyver :  @evgfaer is currently using your desk, and we debugged that together. 

We miss you.

**Comment by takluyver** [comment]
I'm not exactly sure what you mean. Can you give a concrete example that reproduces this problem? There's nothing in flit itself that raises that error - it sounds like something from pip, but I don't know when.

You miss me when there's a problem I might be able to fix, quelle surprise ;-). Nah, I miss you all too.

**Comment by Carreau** [comment]
@evgfaer did make  `__version__ ='snapshot-0.0.1' ` which is not a valid version number (because of snapshot) which fails at wheel install. Of course it is not flit fault, but we should try to warn at build time that the version number might be invalid.

**Comment by takluyver** [comment]
OK, while I wasn't able to reproduce that error message, I did get some errors, and I suspect the difference is due to different versions of pip. I've made a couple of changes in master:

- In the wheel filename, `-` within the distribution name or version should be replaced with `_`. This is in the wheel spec.
- My version of pip only recognises wheel files if the version begins with a number. This isn't in the spec, but pip is rather the de-facto spec, so I've made flit enforce the same restriction. It seems reasonable in any case: versions not starting with a number make it hard to even try to find a sensible ordering.

Can you try with master and check that it does something sensible for you? That will probably just be to throw a clearer error message.
