### ISSUE TITLE
Clarify what choice of license means (and remove Apache?)

### ISSUE THREAD

**Issue by rgommers** [takluyver/flit#54]
The 3 licenses to choose from (MIT/GPL/Apache) are mostly incompatible. And will it be GPL v2 or v3?

Most users won't understand the importance of the choice, so explaining in one sentence per license what the consequence is would be very helpful. Something like:

    MIT: code be used in projects using BSD, GPL or Apache
    GPL: code cannot be used in projects using BSD, MIT or Apache
    Apache: code cannot be used in projects using BSD, MIT or GPL

And Apache is a very much undesired license. Given that pretty much the whole system is MIT/BSD/GPL, including it in this menu of choices is unfortunate. Please consider removing it.

**Comment by Carreau** [comment]
IIRC Thomas used these 3 ones as they where the 3 mainly used license on github:
https://github.com/blog/1964-license-usage-on-github-com

**Comment by takluyver** [comment]
Yep, see http://choosealicense.com/ , a site that Github created.

Apache v2.0 is GPL compatible, and I don't know of any reason why it can't be used from BSD/MIT licensed code.

The template it uses if you select GPL is v3.

I really don't want to get into specifying what can and can't be done with each license, because very quickly you have to get specific about exactly what it means. For instance, readline, which is GPL licensed, is used by the Python shell, which is PSF (like BSD) licensed, and frankly I'm not really sure myself why that's OK. And then you get into the debate about [how the GPL interacts with static and dynamic linking](https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works), and it's not even clear how those terms from C-like languages apply to Python code, and... bah, I'm bored :wink: .

People who have already thought about open source licensing probably have a good idea of what license they want to use. For people who haven't, I think it's more useful to try to summarise the *spirit* of the license than the terms, because there's no good way to do the latter briefly (except perhaps for MIT).

**Comment by Carreau** [comment]
what about say "If you don't know go to  `http://choosealicense.com/`"

**Comment by rgommers** [comment]
> Apache v2.0 is GPL compatible

It's not GPL v2 compatible, see https://gnu.org/licenses/license-list.html#apache2. And here are examples of people needing to hunt down contributors to Python packages to relicense:
https://github.com/pyca/cryptography/issues/1209
https://github.com/pypa/packaging/issues/42

> For people who haven't, I think it's more useful to try to summarise the spirit of the license than the terms

I don't want to start a long discussion, but the above examples clearly show that Apache is a very poor choice for Python packages. So please don't recommend it on equal footing with MIT/GPL without any context.

> because there's no good way to do the latter briefly

So add a few links to good overviews?

**Comment by takluyver** [comment]
I have added a link to http://choosealicense.com for people who want more information.

You can make arguments for and against every license. I've certainly seen projects relicensed from GPL, and I've no doubt projects have been relicensed away from MIT (especially since that's easier). I would rather people didn't create new GPL code, but many people like the GPL, and not without good reasons.

I'm sticking to the shortlist that Github has chosen (MIT, Apache, GPL) for now.

**Comment by rgommers** [comment]
thanks for adding the link
