### ISSUE TITLE
Don't handle uploading

### ISSUE THREAD

**Issue by dstufft** [takluyver/flit#56]
It seems like flit would be better off *not* handling uploading. I think it'd be better to just have it output the wheels and then instruct people to use [twine](https://pypi.python.org/pypi/twine) (eventually will become ``pip upload`` or ``pip publish`` or something) to handle the uploads to PyPI. It seems silly to have a build system handle uploads, especially in a future when there can be multiple different build tools.

**Comment by takluyver** [comment]
I like having a single command to build and upload. If some form of the
proposed standard build tool hooks was adopted, pip upload could use flit
to prepare a wheel and upload it. Until then, I think flit needs to do
uploads itself.

I was also solving an annoyance with twine, which didn't handle package
registration, so one still needed to use distutils to do that. Maybe that
has been fixed since I last tried it.

**Comment by Carreau** [comment]
I'm +1 on @takluyver, I'm not sure how much twine is usable as a library, but having a single extra-flag  to publish is much easier to do and remember that using 2 CL tools. 

Flit also provide some utility to warn you if your package has a name [too close to the ones already on PyPI](https://github.com/takluyver/flit/blob/1767ceb52b2785dd43fbdd42667db8b5ed2e9d30/flit/inifile.py#L159-L160).

Though we can investigate wether we can use twine as a library to do some of the ulpoad work maybe.

**Comment by dstufft** [comment]
Up to y'all of course. FWIW though pip won't ever dispatch to the underlying build tool for upload.

**Comment by Carreau** [comment]
Will pip upload command be available as a library ?

**Comment by dstufft** [comment]
No.

**Comment by dstufft** [comment]
To clarify, pip's only supported API is via CLI. You can shell out to it if you'd like of course.

**Comment by Carreau** [comment]
That make me a bit sad.

Still thanks for the work you are doing on PyPA.

**Comment by dstufft** [comment]
Why does it make you sad? Generally I find it useful to have the package creation and package upload steps separate anyways because it makes it easier to test the actual thing that is going to be uploaded instead of just hoping that two separate invocations of the package creation will create the exact same output.

**Comment by takluyver** [comment]
I see what you're saying, and the first time I release a package, I do
often build a wheel and give it at least a cursory glance before uploading.
But I also think that upload should build a fresh package from the current
source tree, so you don't accidentally upload a package you built before
making a last minute change.

Of course, for minor releases, when I'm not worrying about breaking
packaging, it's also very convenient to upload directly without a separate
build step. And flit aims to make packaging more reliable, because there's
no package_data or manifest.in which you can forget to add things to.

**Comment by Carreau** [comment]
> Generally I find it useful to have the package creation and package upload steps separate anyways because it makes it easier to test the actual thing that is going to be uploaded instead of just hoping that two separate invocations of the package creation will create the exact same output.

Well asking for flit to upload without building is a separate question (which I would agree to have an option for, but I'm not the package owner). 

I'm sad that pip API is only via CLI. I would like to be able to do some things without shelling-out. I can imagine a GUI package manager on top of PIP, and having to actually shell-out and parse the output seem horrific.

I haven't either looked that much into wheels internals, but I could imagine, doing the install/build/whatever step only in memory without hitting filesystem. Which seem hard if you can only shell out to pip.

**Comment by dstufft** [comment]
It's not really possible for pip to (sanely) be used via an API right now because keeping pip inside of a persistent process will cause lots of weird things to happen. A lot of this is due to some caching that ``pkg_resources`` has built into it. As things go on our new PEPs are being implemented largely outside of pip inside of libraries where we can and it makes sense to do so. A larger goal is to make it so that less stuff is implemented inside of pip and pip is really just a CLI wrapper around other libraries like [package](https://pypi.python.org/pypi/packaging).

Anyways, since @takluyver is against this, I'll close this.

**Comment by Carreau** [comment]
Ah, that makes sens. 

I guess if we can move some of the functionality here to pacakge, or another lib I can try to give a hand to do that.
