### ISSUE TITLE
Central sdist / setup.py discussion

### ISSUE THREAD

**Issue by takluyver** [takluyver/flit#74]
I've been asked a few times to provide setup.py files and/or sdists for projects packaged with flit. This is a central place to think about problems and potential solutions. It is _not_ a commitment to add any particular support for this in flit.

The problems that have been encountered are:
- People want to `pip install` directly from a Github URL, which only works if the repository contains a setup.py at the top level.
- People using legacy tools such as buildout may be unable to install wheels (see e.g. pexpect/ptyprocess#31).
- Linux distro packagers have toolchains that expect a source tarball with a setup.py file (e.g. jupyter/testpath#6). I don't have much sympathy with this issue, because I think declarative metadata and standard formats will ultimately make repackaging easier.

Potential solutions to some of these problems:
- [flituptools](https://gist.github.com/takluyver/0a45729a356e002d22e3) is a module which reads metadata from a flit config file and invokes setuptools with it. The idea is that you can check in a setup.py that just calls `flituptools.setup()`, and either copy `flituptools` into your repo, or tell users they need it to pip install directly from Github. However:
  - Packages are only installable with flit already installed, and consequently with Python 3.
  - Eeuw, setuptools.
- [make_sdist.py](https://gist.github.com/takluyver/7c66429a8e7f2b9388b0) is a script I wrote for ptyprocess, to generate a basic sdist from flit metadata. The sdist does not depend on flit, so it can be installed in any version of Python. However:
  - No setup.py in the repo, so it doesn't allow `pip install` directly from Github. If you do generate a setup.py and check it in, you have duplicate information to keep up to date.
  - People ask for things like tests and docs in sdists, so before you know it, you're reinventing `MANIFEST.in`, which really doesn't appeal.
  - Technically Linux distro packagers shouldn't use the sdists, as `setup.py` is generated rather than a source file. In reality, most probably won't notice or won't care.
- @njsmith proposed a new sdist format which would have used a declarative config file to specify the buildsystem to use to make wheels. However:
  - The proposal got mired in different opinions on what it was trying to achieve, and didn't go anywhere.
  - It presumably wouldn't help people with legacy tools, though at least a new standard would provide a better argument for moving to newer tools.
- One could write a setup.py that implements the necessary command line interface for pip ([documented here](http://meetings.copernicus.org/elpub2016/conference/)) without calling into distutils/setuptools (thanks @njsmith for the suggestion). Apparently other projects have done this. However:
  - The pip specification basically says "do what setuptools does" - specifically the `egg_info` command, which creates metadata in setuptools' non-standard format.
    - Perhaps a PR could be made against pip to try `bdist_wheel` first, and not bother with `egg_info` if it succeeds? That would make it easier to integrate.

**Comment by Carreau** [comment]
:cry: :snake: :package:

**Comment by njsmith** [comment]
Been looking at reviving that proposal but yeah it won't be ready in the short term. You're missing at least one option here though: write a script named setup.py that implements the specific options that pip actually calls, and implements them by calling flit instead of using setuptools. There's one example of this in bento, and Robert Collins has a version of this he wrote to shim his version of the new build system interface to run with legacy pip.

**Comment by takluyver** [comment]
Thanks, I've added that idea to the list. I wonder if pip could be patched to try `bdist_wheel` first, and not bother with `egg_info` if it succeeds? That would make it much more palatable.

Let me know if you do revive the sdist 2 proposal.

**Comment by njsmith** [comment]
@takluyver: Well... one of the major remaining points of contention in the build system interface debate is that @rbtcollins considers `egg_info` to be really important. His use case is that he's thinking ahead to when pip gains a real resolver (which is a super important feature that he's also been working on -- resolver = code to actually solve the constraint satisfaction problem and guarantee that all installed packages are compatible, as compared to pip's current horrible hacks that can leave you with inconsistent installations). And when we have this resolver, it'll need to quickly consider many many possible installation sets, and that requires that it have access to the dependency information for different versions of different packages. And for packages that are distributed as sdists instead of wheels, `egg_info` gives a way to get that dependency information that's cheaper than actually building the package. (Recall that at the time `egg_info` is called, pip hasn't actually decided whether to install this package -- and you don't really want to run `bdist_wheel` if it's going to later turn out that you didn't want that version of the package anyway.)

I appreciate the force of this argument, but would rather make `egg_info` support optional to simplify the life of build system authors... so as a build system author you could add support if it makes sense or not, depending on your particular user base (and to what extent they use wheels versus sdists), available development resources, complexity of implementing this thing, etc.

Not sure what the final outcome here will be, but pretty sure the idea of just removing the call to `egg_info` entirely is not going to have an easy path into `pip` :-)

I think actual released versions of pip might in fact be happy if calling `egg_info` generates a `.dist-info` directory. And if that's the case I guess you can always implement `egg_info` by calling `bdist_wheel` and then extracting the `.dist-info` directory ;-)

**Comment by rbtcollins** [comment]
Uhm, @njsmith I think you're out of date :). https://github.com/pypa/interoperability-peps/pull/54/files#diff-4835edef865f75272032e7103376adfdR156 is the current prose in my proposal.

**Comment by njsmith** [comment]
@rbtcollins: Oh, sure, I know it's not literally `egg_info` anymore in your proposal -- but you still have a metadata-query-stage before the wheel-building-stage.

**Comment by rbtcollins** [comment]
Sure, but its PEP-427 - wheel -format already. So yes, making a wheel and extracting the data is in deed very straight forward - I used that in my setuptools_shim (which provides a setup.py for projects using build tools like flit) to generate egg info for older pips.

**Comment by rbtcollins** [comment]
Oh, also - note that patching pip won't get you compat with existing pips. If you only care aboutworking with newer pips, just implementing the abstract build system directly will be much simpler, and you won't need a setup.py in flit using projects at all.

**Comment by takluyver** [comment]
Thanks @rbtcollins , that proposal looks encouraging. It would certainly solve the 'pip install from Github' issue, and having a new standard to point to would be a better answer for people with the other issues.

**Comment by dholth** [comment]
See https://github.com/pypa/pip/issues/3670

Argument against having pip support dist-info as egg-info "there is no tool that does it currently". Please chime in if it interests you.

**Comment by takluyver** [comment]
Thanks for the heads up. I'm currently not planning to implement any support for `setup.py` in flit, because I anticipate lots of user confusion when it doesn't behave *exactly* like a setuptools/distutils setup.py script.

Pip using a standardised output from setup.py would make it slightly more attractive, but I'd rather get one of the build system PEPs (516/517) in and make flit support the declarative config file.

**Comment by minrk** [comment]
It would be really nice if there were a standard way to make sdist and/or setup.py with flit, even if it's not 'active' by default. The `make_sdist.py` script above seems like a really nice solution, and I'd be really happy if every flit-packaged project uploaded an sdist to PyPI with this command.

Even if they don't, uploading a snapshot tarball that requires flit or flit_install_py2 to run would be an improvement. The absence of tarballs on PyPI can get pretty frustrating. Relying on GitHub's archive URLs is not a real solution, as it doesn't (technically) guarantee checksum-stable files, since they are generated on demand.

While I personally don't enjoy the fact that normal Python dev installs don't work with pip packages, I don't think that affects too many people who are users of a given library. It does discourage some potential contributors from participating in flit projects (e.g. me), but the lack of an sdist on PyPI seems like a bigger problem.

**Comment by takluyver** [comment]
I've integrated the `make_sdist.py` script in an experimental [sdist branch](https://github.com/takluyver/flit/tree/sdist). From that branch, you can use it as `python3 -m flit.make_sdist`. It has a few updates compared to the script on gist: scripts, dependencies and package_data should all now work.

It's still quite experimental, but feel free to kick the tyres.

**Comment by takluyver** [comment]
@minrk have you had a try with the integrated `make_sdist` functionality? Or has building conda packages from wheels superseded that?

**Comment by minrk** [comment]
make_sdist.py seemed to be working for me. I can't upload to any flit packages, so I couldn't get farther than local testing. Since the sdist script itself requires flit, it wasn't helping me do conda builds in the absence of flit conda packages.

I do think it's a good idea, though, and I would be very happy to see it included, and for every flit-packaged project to use it. Even if you decide against it, I really think every package on PyPI should publish an sdist, even if you decide against the generated setup.py and the sdist requires flit to build.

**Comment by takluyver** [comment]
OK, thanks. I mostly wanted confirmation that someone other than me had tried making some sdists with it and got them to work.

**Comment by Carreau** [comment]
Should we ask for a flit feedstock ?

**Comment by takluyver** [comment]
On conda-forge? Min prepared one already and it's in staging:
https://github.com/conda-forge/staged-recipes/tree/master/recipes/flit

**Comment by Carreau** [comment]
Oh ! I missed that !

**Comment by takluyver** [comment]
My remaining concern with autogenerating sdists is that people want things like docs and tests in sdists, and I don't want to end up with something like `MANIFEST.in`, for which I have to go and look up the syntax every time I change it.

At the moment, the approach in the `sdist` branch is to look for a short fixed list of relevant files: `tests, docs, LICENSE, README.rst`. We can expand that a bit (e.g. to include `doc` as well as `docs`). Does this approach seem sufficient? Or do we need to think about how people control including and excluding files?

**Comment by njsmith** [comment]
Proposal: the sdist should contain exactly the same files as a clean git
checkout.

I'm not sure that's right, but I'd be curious to know why it's wrong.

**Comment by takluyver** [comment]
I like that as a principle, actually. While I haven't been putting sdists on PyPI, I've suggested that people use the tarballs generated by Github/Gitlab/Bitbucket as the source for downstream packaging.

Practical details to work out:

1. `git archive` can do it very conveniently (something like `git archive HEAD -o dist/flit-0.13.tar.gz --prefix flit-0.13/`), but using that assumes that `git` is on `PATH`, which may be problematic, particularly on Windows. I can't currently think of a clean way to avoid that without adding large new dependencies.
2. I don't want flit to assume the project is in git. We could provide a way to integrate with different VCSs, but ideally I'd like it not to assume that the project is in a VCS at all.

**Comment by FRidh** [comment]
> While I haven't been putting sdists on PyPI, I've suggested that people use the tarballs generated by Github/Gitlab/Bitbucket as the source for downstream packaging.

I'm sure packagers (that includes myself) would prefer to use the real source as well. But we also like to have an index, to automate package updating and retrieval.

I think its good to look at the history of PyPI. At first it was just an index, not providing hosting. However, that has changed over time and now it is primarily for the hosting of sdists and wheels, and not anymore for referring to external locations.

If there would be an index, that would simply refer to source archives, and would have some additional meta data, that would be great. And if that index would also mirror the source archive, even better. But what we have now is an index, that doesn't mirror source archives, but instead requires a portion of a source archive along with some meta data that is put *in* the same archive.

If we would think of a `pip` with PyPI as a source distribution with binary substitutes, the source would be in fact an `sdist`, and not the actual source.

Therefore

> Proposal: the sdist should contain exactly the same files as a clean git
checkout.

is something I think should absolutely happen, together with PEP 516.

**Comment by minrk** [comment]
> While I haven't been putting sdists on PyPI,  I've suggested that people use the tarballs generated by GitHub/GitLab/Bitbucket as the source for downstream packaging.

Having worked on downstream stuff with conda-forge for a bit, I don't like using these. Part of the reason is they are generated on demand and don't guarantee checksum stability, even though in practice these services try to make changing checksums rare. Uploading a 'real' sdist (even if it's the same `git archive` command) solves that problem.

`git archive` works, as long as the repo is git, the package directory is the only thing in the repo, and there are no submodules. That GitHub's download links used `git archive` was a nightmare while IPython used submodules, because we couldn't disable the links that could never produce usable results. I imagine that's not relevant for flit, which only aims to handle the simplest cases.

One naïve sdist is to just include all files, with a few ignores: VCS directories + build/dist, possibly with a `.flitignore` to ignore things flit doesn't already know about (e.g. new VCS). Then it's incumbent upon the caller to make the call in a clean repo, which I think I like better than something like `MANIFEST.in`.

**Comment by takluyver** [comment]
I don't really want `.flitignore`, because it's back to yet another config file. It'd be a more memorable format than MANIFEST.in, but it would normally be the same as `.gitignore`. Then Unix developers would be tempted to symlink them, so it would break on Windows. And git has a way to ignore globs globally (which I use), so we'd probably want something parallel, and it all gets complex in a hurry.

I started thinking about a built-in blacklist of files/directories, but I realised that I'd want to exclude Sphinx's build directory, and there are several different 'common' locations for that (doc vs docs, build vs `_build`...), and that's just one tool. So with any sensible blacklist, most repos are going to want to extend the blacklist.

Are the [Git host] tarballs changeable just because the developer can move the tag? If so, we could get round that by using the commit ID instead. Or can they also change because of changes to the service, even without moving the tag?

While I don't much like git submodules, I wouldn't consider them out of scope for flit. So that's another issue. `git archive` doesn't even have an option for submodules AFAICS, but there are a couple of [git-archive-all](https://github.com/Kentzo/git-archive-all) scripts out there which claim to do it.

I guess we should think about whether we want sdists on PyPI as real source tarballs - in which case, something like `git archive` seems appropriate - or whether it's just a shim for compatibility with existing tools, in which case I'd be more inclined to ship a minimal set of files, and leave out things like docs.

**Comment by minrk** [comment]
> Are the [Git host] tarballs changeable just because the developer can move the tag?

It's because they are generated on-demand programmatically, which is not generally checksum-stable in the long term, even if the git source doesn't change. For a while, GitLab tarball checksums were different on every download, but it's reasonably stable now. GitHub's been better, but has still changed a couple of times, due to changes in git itself, I think.

**Comment by FRidh** [comment]
> Are the [Git host] tarballs changeable just because the developer can move the tag?

In Nixpkgs we record hashes of all archives we refer to. In the past this was an issue with GitHub but this last half a year I've never encountered it. I recall there used to be a difference between the `Releases` and `Tags` tabs, with the `Releases` being (more) stable.

**Comment by takluyver** [comment]
Status update:

- We're still pushing forwards on [PEP 517](https://www.python.org/dev/peps/pep-0517/), which will allow source trees without `setup.py`. There's a reluctance to consider that until PEP 518 is implemented in pip, so I've been [working on that](https://github.com/pypa/pip/pull/4144).
- I'm leaning towards the `make_sdist` option with autogenerated setup.py in the sdist, if I can come up with a solution to the MANIFEST problem that I'm happy with.

**Comment by takluyver** [comment]
I've been thinking about the MANIFEST question, and I think I'll settle for using information from the VCS to determine what goes into the sdist. I'll support git and hg at first, and leave it open to adding support for other VCSs later. You will need to be in a recognised VCS to make an sdist, but making wheels will still work without it.

I'm still thinking about how exactly to use the VCS. I see three approaches:

1. Let the VCS do most of the work, e.g. with `git archive`. Easy, but gives us little control of the process. IIRC `git archive` doesn't work with submodules. (Maybe flit just doesn't support submodules? I don't fancy trying to handle them in any of these options)
2. Ask the VC for a positive list of files tracked, e.g. with `git ls-tree` or `git ls-files` (I need to work out how these two differ).
3. Filter the files ourselves using e.g. `.gitignore`. This has the advantage that it would work from a Github tarball download, but the (arguable) disadvantage that it would include files neither tracked nor ignored - it's not unusual for me to have some junk files in a repo working directory which I have neither committed nor ignored. There are also IDE files which I configure git to ignore globally, so they're not listed in the repo's `.gitignore`.

I'm leaning towards approach 2.

**Comment by FRidh** [comment]
I agree with @njsmith and see no point in `MANIFEST`. Just use what's in a clean checkout. 

In Nixpkgs we're typically still using PyPI sdists as input, but would prefer to use the repositories because sdists often do not include tests.

**Comment by takluyver** [comment]
No problem. I think that's basically what I want to do. I'm considering different ways to figure out what files would be in a clean checkout.

**Comment by njsmith** [comment]
Option 2 seems like a good idea to me. Perfectly implementing .gitignore semantics sounds highly non trivial.

You might also want to query the vcs for untracked files and if any are found then force the user to decide what they want to do with them (e.g. by trying again with `flit sdist --ignore-untracked`), to avoid the very common error of forgetting to add some new file before a release and it works on the Dec's computer but nowhere else.

And it might make sense for the sdist step to create a private representation of the file list and include it in the tarball, and the wheel build step to use this list so that sdist-to-wheel process is guaranteed to produce the same results as the vcs-to-wheel process would have.

**Comment by FRidh** [comment]
How about by default including all files except dotfiles? Flit could warn or error if certain files (e.g .pyc) are included. Optionally, there would be a --files option where you can simply list files that need to be included, with the only requirement being that their either at the root or below. That way, people can write whatever filter they like.

While creating bad archives or wheels due to working in a dirty tree unfortunately sometimes happens, I think that is something outside the scope of flit to solve and up to the developer to take care off.

> And it might make sense for the sdist step to create a private representation of the file list and include it in the tarball, and the wheel build step to use this list so that sdist-to-wheel process is guaranteed to produce the same results as the vcs-to-wheel process would have.

+1

**Comment by takluyver** [comment]
Nathaniel:
> it might make sense for the sdist step to create a private representation of the file list and include it in the tarball, and the wheel build step to use this list so that sdist-to-wheel process is guaranteed to produce the same results as the vcs-to-wheel process would have.

I like the idea of having a check that the wheel build isn't including anything that's not in the sdist. I might implement it a bit differently, though.

> How about by default including all files except dotfiles?

I want to make it easier for package authors to do things right. E.g. built HTML documentation shouldn't be included in a source dist, but it's not a dotfile.

> Flit could warn or error if certain files (e.g .pyc) are included.

Unfortunately I think there's too much diversity of files that shouldn't be included to rely on a fixed blacklist (or a fixed whitelist, for that matter).

> Optionally, there would be a --files option where you can simply list files that need to be included

This is essentially the MANIFEST approach that's used with `setup.py` packaging. I don't want to replicate that.

I think I'm happy with using the VCS to work out what files to include in the sdist. I'm going to have a go at coding it.

**Comment by takluyver** [comment]
PR #106 now contains the code for making sdists, cleaned up and polished somewhat. It seems to be working nicely for the modules I've tried it with. Feel free to review it and try it out!

**Comment by warsaw** [comment]
One of the use cases I've been struggling with is to integrate tox with a setup.py-less project containing a pyproject.toml file.  I haven't had any luck with that, so as an interim solution I thought about generating a setup.py from a pyproject.toml file.   Maybe that's crazy talk though. :)

**Comment by takluyver** [comment]
Flit actually does generate a setup.py when you make an sdist.

I'm not making it easy to generate a `setup.py` by itself to check in to a VCS, because it's a poor user experience (you have to maintain setup.py and MANIFEST.in in addition to flit's metadata), and because I want there to be some pressure on tools like pip and tox to support `pyproject.toml`. But if you really want to have setup.py in the repo, you can build an sdist and extract it from there.

**Comment by takluyver** [comment]
Between the sdist support (which is now released) and the acceptance of PEPs 518 and 517, I think this can be closed. There's still some way to go on other tools supporting the 518/517 interface, but it exists and flit supports it.

**Comment by warsaw** [comment]
I think it's fine.  I don't expect us to change our pyproject.toml very often, so a manual process to generate a setup.py just for the sake of tox could work for now.  I'll give it a try -- thanks!

**Comment by warsaw** [comment]
So this works except for one small detail; the generated `setup.py` uses `distutils.core.setup()` instead of `setuptools.setup()`.  This breaks sphinx documentation builds because `python3 setup.py build_sphinx` isn't a valid command despite all the correct dependencies being involved.  Edit the setup.py over to use setuptools and all is good.

What would make the transition easier would be for `flit sdist` to take two arguments.  First, would be a flag to use setuptools instead of distutils.core.  The second would be to designate an output location for the .tar.gz file or the dist directory.  The latter would allow me to pipe the output of `flit sdist` to say a script that extracts just the setup.py into the current directory.  I think those two things would allow me to automate the whole process.

**Comment by takluyver** [comment]
I should probably change it to use `setuptools` all the time, rather than adding an option. Pip forces it to use setuptools anyway, even when it imports distutils. I just try to avoid writing `import setuptools` as much as possible.

For automation, you could use the PEP 517 API. Untested, but something like this:

```python
import os
import tarfile
import tempfile
import flit.buildapi

with tempfile.TemporaryDirectory() as td:
    filename = flit.buildapi.build_sdist(td)
    tf = tarfile.open(os.path.join(td, filename))
```

**Comment by merwok** [comment]
I’m curious: what’s the benefit of calling `setup.py build_sphinx` instead of `make html` or `sphinx-build` directly?

**Comment by warsaw** [comment]
On Dec 6, 2017, at 14:14, Éric Araujo <notifications@github.com> wrote:
> 
> I’m curious: what’s the benefit of calling setup.py build_sphinx instead of make html or sphinx-build directly?

Good idea; not `make html` but `sphinx-build` should work since tox will enter the venv first and find the one it installed through the sphinx dep.  The main thing is that we use the Python version from our tox.ini file’s `docs` environment, and that should do it.

**Comment by warsaw** [comment]
On Dec 6, 2017, at 13:40, Thomas Kluyver <notifications@github.com> wrote:
> 
> For automation, you could use the PEP 517 API. Untested, but something like this:
> 
> import
>  os
> 
> import
>  tarfile
> 
> import
>  tempfile
> 
> import
>  flit.buildapi
> 
> 
> with tempfile.TemporaryDirectory() as
>  td:
>     filename
> =
>  flit.buildapi.build_sdist(td)
>     tf
> = tarfile.open(os.path.join(td, filename))

That works pretty well except that I have to make sure there’s no existing setup.py in the current directory or tracked by git.  Otherwise flit will either use the existing setup.py or throw a VCSError.  But that’s fine; I can work with that.

Thanks!

**Comment by warsaw** [comment]
Well, it was a little tricky, but here’s what I came up with:

https://gitlab.com/python-devs/importlib_resources/blob/master/update-setup.py

**Comment by takluyver** [comment]
Nice!

If you're going to the trouble of subclassing SdistBuilder, it's probably simpler to use that interface directly, which saves monkeypatching it. It uses pathlib objects.

```python
sdist = SneakySdistBuilder(Path('pyproject.toml')).build(Path(td))
tarfile.open(str(sdist))
```

I was pointing to the PEP 517 interface because that's more likely to stay consistent, but if you need to monkeypatch to use it, you're already relying on the underlying APIs.

Other than the PEP 517 interface (exposed as `flit.buildapi`), I don't consider any of flit's Python API to be public. I don't expect what you're doing to break any time soon, but be aware that you may need to update the script as flit evolves. Hopefully tox will add support for pyproject.toml, so you won't need it for long.

Finally, you may need to regenerate the setup script when the version number changes, or if you add subpackages, or folders of package data. And possibly some other conditions that haven't occurred to me. It's drawing on more information than just `flit.ini`.

**Comment by warsaw** [comment]
@takluyver Thanks very much for the detailed response.
