### ISSUE TITLE
test flit wheels with 'wheel unpack'

### ISSUE THREAD

**Issue by dholth** [takluyver/flit#76]
The other day I tried to 'wheel unpack' a flit wheel, and it had what is probably a trivial metadata but that prevented it from verifying.

**Comment by takluyver** [comment]
Thanks for letting me know. I've just tried `wheel unpack` on a fresh wheel of flit itself, and there was no problem. What wheel were you trying with, and what error did you get?

In flit < 0.8.1, the hashes in the RECORD file were wrongly written in hex rather than url-safe base64 (I hadn't spotted earlier because pip apparently doesn't check them). Could this be the issue? If so, it's probably just a matter of regenerating the wheel with the latest version of flit.

**Comment by dholth** [comment]
That's probably all it was. Thanks for looking into it.
