### ISSUE TITLE
test seek closed file

### ISSUE THREAD

**Issue by Carreau** [takluyver/flit#92]
Narrowed down to `test_wheel`, in particular the following:

```
def test_entry_points_conflict():
    clear_samples_dist()
    with pytest.raises(EntryPointsConflict):
        wheel_main(samples_dir / 'entrypoints_conflict.ini')
```

If one record warnings:

```
py.test -p recwarn tests/test_wheel.py
=================================================================== test session starts ===================================================================
platform darwin -- Python 3.5.2, pytest-3.0.4.dev, py-1.4.31, pluggy-0.4.0
rootdir: /Users/bussonniermatthias/dev/flit, inifile:
plugins: warningsfilters-0.0.1, xonsh-0.4.6
collected 1 items

tests/test_wheel.py .

=== 1 passed in 0.13 seconds  ===
Exception ignored in: <bound method ZipFile.__del__ of <zipfile.ZipFile [closed]>>
Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/zipfile.py", line 1595, in __del__
    self.close()
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/zipfile.py", line 1607, in close
    self.fp.seek(self.start_dir)
ValueError: seek of closed file
```

You were involved in the zipfile patch, so pinging you first. I'm gonna assume a `self._fpclose(self.fp)` is called without setting `self.fp` to None. 

I don't see where except maybe `zef_file.close()`...

**Comment by takluyver** [comment]
I spotted this in a test run last night, but was too tired to look into it. Thanks for the reminder!

I think I understand it now.

* `zf._fpclose()` does not close the underlying file, because we pass in a file handle, so `self._filePassed == 1`.
* However, the context manager in `wheel_main` will close the underlying file handle.
* If an error occurs while building the wheel, `WheelBuilder.build()` never calls `self.wheel_zip.close()`
* When `wheel_main` exits, the WheelBuilder goes out of scope, and is garbage collected along with its zip file, after the context manager has closed the underlying file handle.

So it should be a simple bit of try/finally. Fix coming up...

**Comment by takluyver** [comment]
Yup, that seemed to do it.

**Comment by Carreau** [comment]
Ok, great !
